# Generated by Django 5.2.6 on 2025-09-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_section', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChapterLike',
        ),
    ]
